# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"is_silence": "00_core.ipynb",
         "load_file": "01_chunkadelic.ipynb",
         "makedir": "01_chunkadelic.ipynb",
         "blow_chunks": "01_chunkadelic.ipynb",
         "process_one_file": "01_chunkadelic.ipynb",
         "main": "01_chunkadelic.ipynb"}

modules = ["core.py",
           "chunkadelic.py"]

doc_url = "https://drscotthawley.github.io/shazbot/"

git_url = "https://github.com/drscotthawley/shazbot/tree/master/"

def custom_doc_links(name): return None
