# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"is_silence": "00_core.ipynb",
         "HostPrinter": "00_core.ipynb",
         "save": "00_core.ipynb",
         "n_params": "05_blocks_utils.ipynb",
         "freeze": "00_core.ipynb",
         "load_file": "01_chunkadelic.ipynb",
         "makedir": "01_chunkadelic.ipynb",
         "blow_chunks": "01_chunkadelic.ipynb",
         "process_one_file": "01_chunkadelic.ipynb",
         "main": "03_train_audio_algebra.ipynb",
         "PadCrop": "02_data.ipynb",
         "PhaseFlipper": "02_data.ipynb",
         "FillTheNoise": "02_data.ipynb",
         "RandPool": "02_data.ipynb",
         "NormInputs": "02_data.ipynb",
         "Mono": "02_data.ipynb",
         "Stereo": "02_data.ipynb",
         "RandomGain": "02_data.ipynb",
         "MultiStemDataset": "02_data.ipynb",
         "DiffusionDVAE": "03_train_audio_algebra.ipynb",
         "setup_weights": "03_train_audio_algebra.ipynb",
         "ad_encode_it": "03_train_audio_algebra.ipynb",
         "EmbedBlock": "03_train_audio_algebra.ipynb",
         "AudioAlgebra": "03_train_audio_algebra.ipynb",
         "demo": "03_train_audio_algebra.ipynb",
         "get_stems_faders": "03_train_audio_algebra.ipynb",
         "embeddings_table": "04_viz.ipynb",
         "proj_pca": "04_viz.ipynb",
         "pca_point_cloud": "04_viz.ipynb",
         "spectrogram_image": "04_viz.ipynb",
         "audio_spectrogram_image": "04_viz.ipynb",
         "tokens_spectrogram_image": "04_viz.ipynb",
         "append_dims": "05_blocks_utils.ipynb",
         "train_mode": "05_blocks_utils.ipynb",
         "eval_mode": "05_blocks_utils.ipynb",
         "ema_update": "05_blocks_utils.ipynb",
         "EMAWarmup": "05_blocks_utils.ipynb",
         "InverseLR": "05_blocks_utils.ipynb",
         "init_jukebox_sample_rate": "06_icebox.ipynb",
         "audio_for_jbx": "06_icebox.ipynb",
         "load_audio_for_jbx": "06_icebox.ipynb",
         "JUKEBOX_SAMPLE_RATE": "06_icebox.ipynb",
         "IceBoxEncoder": "06_icebox.ipynb"}

modules = ["core.py",
           "chunkadelic.py",
           "data.py",
           "train_audio_algebra.py",
           "viz.py",
           "blocks_utils.py",
           "icebox.py"]

doc_url = "https://drscotthawley.github.io/shazbot/"

git_url = "https://github.com/drscotthawley/shazbot/tree/master/"

def custom_doc_links(name): return None
